/**
 * Master list of every English UI string that should be translated when the
 * user picks a non-English language. The full array is sent to the /translate
 * endpoint once per language and cached. Components call `t("english string")`
 * to render the translated version.
 *
 * Keep entries here in lockstep with what components pass to `t(...)` —
 * unknown keys fall back to the English source, so a missed entry just shows
 * English instead of breaking.
 */
export const UI_STRINGS = [
  // ===== Header / general chrome =====
  "Turn any lecture into a study environment",
  "Lecture loaded",
  "Process another lecture",
  "New lecture",
  "History",
  "Try another URL",
  "We couldn't process that lecture",
  "Translating to",
  "Generate Study Environment",
  "Paste a YouTube lecture URL...",

  // ===== Tabs =====
  "Outline",
  "Analysis",
  "Flashcards",
  "Search",
  "Quiz",
  "Mind Map",

  // ===== Bloom's level names =====
  "Remember",
  "Understand",
  "Apply",
  "Analyze",
  "Evaluate",
  "Create",

  // ===== Bloom's gerunds =====
  "Remembering",
  "Understanding",
  "Applying",
  "Analyzing",
  "Evaluating",
  "Creating",

  // ===== Cognitive load =====
  "Cognitive load:",
  "Low",
  "Medium",
  "High",
  "Slow down on high-load moments — they need extra processing time.",
  "High load — slow down to process",

  // ===== Search =====
  "Ask a question or search lecture content...",

  // ===== Quiz mode labels =====
  "Bottom Up",
  "Top Down",
  "Top Down (Productive Failure)",
  "Mastery",
  "Mastery Mode",
  "Productive Failure",
  "Build Up",
  "Quiz mode",
  "How do you want to learn today?",
  "Build up — earn each Bloom's level in turn.",
  "Productive failure — start at Evaluate, scaffold down.",
  "Adaptive stream — difficulty rises with your accuracy.",
  "Ready when you are",
  "Start Quiz",
  "Try the hardest one",
  "Mastery Mode adapts to you — start at Remember and climb.",
  "We'll pull a question from your flashcards and launch instantly.",
  "Exit",
  "Close",
  "Cancel",
  "Save",
  "Create",

  // ===== Lecture Profile =====
  "Lecture Profile",
  "Dominant level:",
  "Bloom's distribution",
  "— click a segment for tailored study tips",
  "Topics at this level",
  "Recommended Tools for This Level",
  "How to study this lecture",
  "Suggested Tools for This Lecture",
  "Study Tips for",

  // Profile tools / recommendations
  "Open Flashcards",
  "Read 90-sec summary",
  "Read full summary",
  "Browse Outline",
  "Start Bottom Up quiz",
  "Jump to Outline examples",
  "Open Mind Map",
  "Try Top Down quiz",
  "Start Mastery Mode",
  "Search lecture moments",
  "Start with the 90-second summary to map the terrain",
  "Drill the Flashcards tab for spaced recall",
  "Run Bottom Up quiz mode to climb from Remember to Apply",
  "Open the Mind Map to see how concepts connect",
  "Use Top Down quiz mode to start from Evaluate and scaffold down",
  "Read the Full summary to get the argumentative throughline",
  "Skim the 5-minute summary for the procedure",
  "Run Mastery Mode quiz — it adapts difficulty as you go",
  "Use the Outline tab to jump to the worked-example moments",
  "Read the 5-minute summary first",
  "Use Mastery Mode quiz for an adaptive mix across Bloom's levels",
  "Revisit Flashcards for any concepts you missed",
  "This lecture is concept- and definition-heavy. Start by locking in the vocabulary and core facts, then build up to applying them. Repetition matters more than synthesis here.",
  "This lecture lives in higher-order territory — judgment, analysis, and trade-offs. Don't try to memorize first; wrestle with the reasoning early so the structure sticks.",
  "This lecture is procedure- and worked-example heavy. You'll learn fastest by doing, not just reading — get into practice problems quickly and review feedback closely.",
  "This lecture mixes recall and reasoning fairly evenly. A balanced approach works best — get the core ideas in place, then stress-test them with mixed-difficulty practice.",

  // ===== Study tip body text (per Bloom level) =====
  "Use the Flashcards tab to drill definitions. Focus on the 90-second summary first to anchor the vocabulary.",
  "Read the full summary section for these topics, then try explaining each one out loud in your own words.",
  "Use the Bottom Up quiz mode for these topics and work through the worked examples in the outline.",
  "Use the Mind Map to draw connections between these concepts, then try the Top Down quiz mode.",
  "Use Mastery Mode and push through to the open-ended justification questions for these topics.",
  "These are the highest-order concepts in the lecture. After quizzing, try adding your own nodes to the Mind Map.",

  // ===== Bloom level descriptions =====
  "Recall facts, terms, and basic concepts from memory. The foundation of all higher-order thinking.",
  "Explain ideas in your own words and grasp meaning. Demonstrates comprehension beyond memorization.",
  "Use what you've learned in new situations. Transfer knowledge to solve concrete problems.",
  "Break down information and examine relationships between ideas. Find patterns, causes, and structure.",
  "Judge, critique, and defend positions using evidence. Weigh trade-offs and assess validity.",
  "Generate original work by combining ideas in new ways. The most demanding cognitive level.",

  // ===== Tooltip copy =====
  "Bloom's Revised Taxonomy (Anderson & Krathwohl, 2001) classifies thinking into 6 levels from basic recall (Remember) to complex creation (Create). Higher levels require deeper understanding.",
  "Bloom's Revised Taxonomy (Anderson & Krathwohl, 2001) is a hierarchical framework classifying cognitive learning into six levels: Remember, Understand, Apply, Analyze, Evaluate, and Create. Originally developed by Benjamin Bloom in 1956 and updated in 2001, it is widely used by educators to design curricula and assessments that develop higher-order thinking skills.",
  "Bloom's Revised Taxonomy (Anderson & Krathwohl, 2001) classifies thinking into six cognitive levels from basic recall to complex creation. NebulaLearn calibrates every quiz question to the Bloom's level of the source content — so you're always being tested at the right cognitive depth.",
  "Immediate feedback accelerates learning by correcting misconceptions before they solidify — research shows it improves retention by up to 25% compared to delayed feedback (Hattie & Timperley, 2007). End of Quiz mode reduces interruptions and simulates exam conditions, helping students build focus and self-assessment skills.",
  "Productive Failure is a learning design developed by Dr. Manu Kapur (ETH Zürich). His research found that students who attempt complex problems before receiving instruction outperform those taught conventionally — developing deeper conceptual understanding and better transfer skills. Source: Kapur, M. (2016). Examining Productive Failure, Constructive Failure, and Instructive Failure. Educational Psychologist, 51(2).",
  "The Build Up approach is grounded in scaffolding theory (Vygotsky, 1978) and mastery learning research (Bloom, 1968). Students build foundational knowledge before advancing to complex tasks, staying within their Zone of Proximal Development. Research shows scaffolded learning improves both confidence and long-term retention, particularly for students encountering unfamiliar material. Source: Wood, Bruner & Ross (1976). The role of tutoring in problem solving. Journal of Child Psychology and Psychiatry, 17(2).",
  "Cognitive Load Theory (Sweller): High load sections require more mental effort. Slow down and review these moments.",
  "Derived from the highest Bloom's level chunks in this lecture — the concepts that require the most sophisticated thinking.",
  "Mastery Mode is based on Benjamin Bloom's Learning for Mastery model (1968), which found that 95% of students can achieve high levels of learning when given adequate time and appropriate instruction. Combined with spaced repetition principles (Ebbinghaus, 1885), the adaptive difficulty in Mastery Mode ensures concepts are reinforced at increasing cognitive depth — mirroring how long-term memory consolidation actually works.",

  // ===== Key Takeaways =====
  "Key Takeaways",
  "Summary",
  "Full Notes",
  "Section-by-section breakdown of the lecture.",

  // ===== Mind Map =====
  "Mind map",
  "Concept hierarchy for this lecture",
  "Drag the background to pan, scroll to zoom. Drag nodes to rearrange. Hover a node and click + to add your own.",
  "Explore",
  "Relabel",
  "Reset",
  "Reset Positions",
  "Reset Notes",
  "Reset Custom Nodes",
  "Reset Everything",
  "Save map",
  "Your concept",
  "Lecture",
  "Topic",
  "Concept",
  "Concept name",
  "Your notes",
  "Add your thoughts, connections, or study notes…",
  "Jump to Video",
  "Delete concept",
  "Rename this concept",
  "New concept",
  "Restore",
  "Maximize",

  // ===== Flashcards =====
  "Create Flashcard",
  "Edit Flashcard",
  "Create your first flashcard to start studying.",
  "No flashcards available.",
  "No flashcards yet",
  "Card",
  "card",
  "cards",
  "in this deck",
  "Step",
  "Question",
  "Answer",
  "Flip card",
  "Quiz me on this",
  "Edit flashcard",
  "Standard",
  "Question & answer",
  "Step Sequence",
  "Ordered procedure",
  "Problem prompt",
  "What's the question?",
  "e.g. Solve a quadratic equation by factoring",
  "The correct answer",
  "Formula (optional)",
  "e.g. F = m·a",
  "Cards with a formula appear in Formula Mode quizzes.",
  "Ordered steps",
  "Multi-path (any valid order accepted)",
  "Move step up",
  "Move step down",
  "Remove step",
  "Add step",
  "Step Sequence cards appear in the quiz's \"Step Ordering\" mode.",
  "Bloom's level",
  "Timestamp (optional)",
  "e.g. 3:24",
  "Delete",
  "Formula",
  "Steps",

  // ===== Bottom Up Quiz =====
  "Bottom-up build",
  "Earn your way up Bloom's taxonomy, one level at a time.",
  "About Bloom's Taxonomy",
  "Mastery achieved",
  "All levels demonstrated",
  "Recall",
  "Is the following claim correct?",
  "True",
  "False",
  "Next level",
  "Explain in your own words",
  "Briefly restate the key idea behind the answer.",
  "In a sentence or two...",
  "Pick the best answer",
  "Apply what you know to choose the right option.",
  "Break it down",
  "What underlying concepts and relationships make this answer correct?",
  "List the parts and how they connect...",
  "Defend your reasoning",
  "Why is this the correct explanation, and not an alternative?",
  "Write your justification here...",
  "Submit & finish",
  "Evaluating...",
  "Correct",
  "Not quite",
  "Answer recorded",
  "Why:",
  "Correct answer:",
  "Correct explanation",
  "Next question",
  "Level",
  "of",

  // ===== Top Down Quiz =====
  "Top-down mastery",
  "Start at the top. We scaffold down only if you ask.",
  "Hint Unlocked",
  "Foundational check — true or false?",
  "Proposed answer",
  "Narrow it down — which is the strongest answer?",
  "Each option is a plausible read of the question. Pick the one that holds up under scrutiny.",
  "Show foundational check",
  "What concepts are relevant here?",
  "Free-write the ideas, terms, or relationships you'd need.",
  "List the concepts that come to mind...",
  "Still stuck — show options",
  "Why is this the correct explanation, and not an alternative? Justify it.",
  "I'm stuck, break it down for me",
  "Struggling a bit longer improves retention.",
  "Submit Justification",
  "Are you sure?",
  "Research shows that productive struggle leads to better long-term memory. Try a bit longer?",
  "Keep trying",
  "Break it down",
  "Response evaluated",
  "Learning outcome achieved",
  "Score:",
  "Bloom level demonstrated:",
  "✅ What you got right",
  "❌ Where it breaks down",
  "What to improve",
  "Learning outcome",
  "Verdict:",

  // ===== Mastery Mode Quiz =====
  "Mastery mode",
  "3 in a row levels you up. One miss drops you back half a level.",
  "Streak",
  "acc",
  "End quiz",
  "Answers will be reviewed in one summary at the end.",
  "True or False",
  "Write your reasoning here...",
  "Submit",
  "Evaluating…",
  "Correct — mastery increased",
  "Not quite — mastery dropped half a level",
  "Answer recorded. Loading next question…",
  "Quiz complete",
  "overall · peak level",
  "Performance by Bloom's level",
  "Study these topics",
  "Missed at",
  "level",
  "All questions & feedback",
  "questions",
  "question",
  "Your answer:",
  "Correct:",
  "Start a new run",
  "Loading questions…",
  "On fire — five in a row. Push for the next level.",
  "Three in a row. The model in your head is solidifying.",
  "Strong work. You're consistently picking the right reasoning.",
  "Nice. Keep going to lock the concept in.",
  "One slip — you've been solid overall. Read the explanation and keep going.",
  "Worth slowing down on this one. Re-read the explanation and try the next.",
  "These are tough — that's the point. Productive struggle is how mastery sticks.",
  "Question",
  "current level:",

  // ===== Proof Mode Quiz =====
  "Justify the step",
  "What comes next?",
  "Find the flaw",
  "Choose the strategy",
  "Theorem",
  "Which proof strategy is the strongest fit for this theorem?",
  "One step contains an unjustified leap. Which one?",
  "Which justification supports the highlighted step?",
  "Given the proof so far, which step comes next?",
  "Full Proof — annotated",
  "Annotation",
  "Done",
  "Proof Mode —",
  "answered",
  "Next",
  "Show me the full proof",
  "Explanation:",

  // ===== Step Ordering Quiz =====
  "Step Ordering · Card",
  "Drag the steps into the correct order, then submit.",
  "Multiple valid orderings are accepted.",
  "Move up",
  "Move down",
  "Reshuffle",
  "Submit order",
  "Your approach is valid. Here's another way to think about it:",
  "Perfect — every step is in the right place.",
  "steps were in the correct position.",
  "This problem has multiple correct orderings. Compare your sequence with the canonical one below.",
  "Alternative sequence",
  "Correct sequence",
  "Cognitive skill developed",
  "Sequencing trains analytical thinking — breaking a procedure into ordered components and reasoning about dependencies.",
  "Putting steps in the right order trains application — using a procedure correctly in context.",
  "Try again",
  "Next problem",
  "Finish",
  "No step-sequence flashcards available. Add one in the Flashcards tab to use Step Ordering mode.",
  "Back",
  "About Key Takeaways",

  // ===== Summary depth toggle =====
  "90 Seconds",
  "5 Minutes",
  "Full",
  "No summary available.",

  // ===== Misc additional quiz copy =====
  "About feedback timing",
  "About Bloom's Taxonomy",
  "About cognitive load",
  "Feedback:",
  "Immediate",
  "End of Quiz",
  "Next question",
  "Could not evaluate response.",
  "Request failed",
] as const;

export type UIString = (typeof UI_STRINGS)[number];
